#!/usr/bin/ruby
@rc_file_path = "#{ENV['HOME']}/.croxy_history"

def optimize(options)
  show_help if ARGV.empty?

  ARGV.delete('curl')

  if ARGV.include?('-H')
    indexes = ARGV.map.with_index{|e, i| e == "-H" ? i : nil}.compact
    indexes.each do |i|
      ARGV[i+1] = "\"#{ARGV[i+1]}\""
    end
  end

  ARGV.join(' ')
end

def exec_curl
  curl_options = optimize(ARGV)

  File.open(@rc_file_path, "a") do |f|
    f.puts curl_options
  end

  puts `curl #{curl_options}`
end

def show_help
  puts "croxy <curl-options>: exec curl with options"
  puts
  puts "croxy help"
  puts "  -l: show saved curl lists"
  puts "  -e: edit .croxy_history"
  exit
end

case ARGV[0]
when "-h"
  show_help
when "-l"
  puts File.readlines(@rc_file_path).sort
when "-e"
  `vim #{@rc_file_path}`
else
  exec_curl
end
