#!/usr/bin/ruby
@rc_file_path = "#{ENV['HOME']}/.croxyrc"

def optimize(options)
  show_help if ARGV.empty?

  ARGV.delete('curl')

  i = ARGV.index("-H")
  ARGV[i+1] = "\"#{ARGV[i+1]}\""

  ARGV.join(' ')
end

def exec_curl
  curl_options = optimize(ARGV)

  File.open(@rc_file_path, "a") do |f|
    f.puts curl_options
  end

  puts `curl #{curl_options}`
end

def show_help
  puts "ruby croxy.rb <options>: exec curl with options"
  puts
  puts "croxy help"
  puts "  -l: show saved curl lists"
  puts "  -e: edit .croxyrc"
  exit
end

case ARGV[0]
when "-h"
  show_help
when "-l"
  File.open(@rc_file_path, "r") do |f|
    f.each_line{|line| puts line}
  end
when "-e"
  exec "vi #{@rc_file_path}"
else
  exec_curl
end
